stages:
  - build

build:alpine:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker build -t ${CI_REGISTRY_IMAGE}/alpine:latest -f Dockerfile_alpine .
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
    - docker tag ${CI_REGISTRY_IMAGE}/alpine:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-alpine
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_SECRET}
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}/alpine:latest
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-alpine

build:debian:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/debian:latest -f Dockerfile_debian .
    - docker build -t ${CI_REGISTRY_IMAGE}/debian/buster:latest -f Dockerfile_debian_buster .
    - docker build -t ${CI_REGISTRY_IMAGE}/debian/stretch:latest -f Dockerfile_debian_stretch .
    - docker build -t ${CI_REGISTRY_IMAGE}/debian/bullseye:latest -f Dockerfile_debian_bullseye .
    - docker tag ${CI_REGISTRY_IMAGE}/debian:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-debian
    - docker tag ${CI_REGISTRY_IMAGE}/debian/buster:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-debian-buster
    - docker tag ${CI_REGISTRY_IMAGE}/debian/stretch:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-debian-stretch
    - docker tag ${CI_REGISTRY_IMAGE}/debian/bullseye:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-debian-bullseye
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_SECRET}
    - docker push ${CI_REGISTRY_IMAGE}/debian:latest
    - docker push ${CI_REGISTRY_IMAGE}/debian/stretch:latest
    - docker push ${CI_REGISTRY_IMAGE}/debian/buster:latest
    - docker push ${CI_REGISTRY_IMAGE}/debian/bullseye:latest
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-debian
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-debian-stretch
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-debian-buster
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-debian-bullseye

build:ubuntu:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/ubuntu:latest -f Dockerfile_ubuntu .
    - docker build -t ${CI_REGISTRY_IMAGE}/ubuntu/16.04:latest -f Dockerfile_ubuntu_1604 .
    - docker build -t ${CI_REGISTRY_IMAGE}/ubuntu/18.04:latest -f Dockerfile_ubuntu_1804 .
    - docker build -t ${CI_REGISTRY_IMAGE}/ubuntu/20.04:latest -f Dockerfile_ubuntu_2004 .
    - docker tag ${CI_REGISTRY_IMAGE}/ubuntu:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-ubuntu
    - docker tag ${CI_REGISTRY_IMAGE}/ubuntu/16.04:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-ubuntu-16.04
    - docker tag ${CI_REGISTRY_IMAGE}/ubuntu/18.04:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-ubuntu-18.04
    - docker tag ${CI_REGISTRY_IMAGE}/ubuntu/20.04:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-ubuntu-20.04
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_SECRET}
    - docker push ${CI_REGISTRY_IMAGE}/ubuntu:latest
    - docker push ${CI_REGISTRY_IMAGE}/ubuntu/16.04:latest
    - docker push ${CI_REGISTRY_IMAGE}/ubuntu/18.04:latest
    - docker push ${CI_REGISTRY_IMAGE}/ubuntu/20.04:latest
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-ubuntu
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-ubuntu-16.04
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-ubuntu-18.04
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-ubuntu-20.04

build:centos:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/centos:latest -f Dockerfile_centos .
    - docker build -t ${CI_REGISTRY_IMAGE}/centos/8:latest -f Dockerfile_centos_8 .
    - docker build -t ${CI_REGISTRY_IMAGE}/centos/7:latest -f Dockerfile_centos_7 .
    - docker tag ${CI_REGISTRY_IMAGE}/centos:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-centos
    - docker tag ${CI_REGISTRY_IMAGE}/centos/8:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-centos-8
    - docker tag ${CI_REGISTRY_IMAGE}/centos/7:latest ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-centos-7
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_SECRET}
    - docker push ${CI_REGISTRY_IMAGE}/centos:latest
    - docker push ${CI_REGISTRY_IMAGE}/centos/8:latest
    - docker push ${CI_REGISTRY_IMAGE}/centos/7:latest
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-centos
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-centos-8
    - docker push ${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest-centos-7
