stages:
  - build
  - external_build

build:alpine:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker build -t ${CI_REGISTRY_IMAGE}/alpine:latest -f Dockerfile_alpine .
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}/alpine:latest

build:debian:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/debian:latest -f Dockerfile_debian .
    - docker build -t ${CI_REGISTRY_IMAGE}/debian/buster:latest -f Dockerfile_debian_buster .
    - docker build -t ${CI_REGISTRY_IMAGE}/debian/stretch:latest -f Dockerfile_debian_stretch .
    - docker build -t ${CI_REGISTRY_IMAGE}/debian/bullseye:latest -f Dockerfile_debian_bullseye .
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}/debian:latest
    - docker push ${CI_REGISTRY_IMAGE}/debian/stretch:latest
    - docker push ${CI_REGISTRY_IMAGE}/debian/buster:latest

build:ubuntu:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/ubuntu:latest -f Dockerfile_ubuntu .
    - docker build -t ${CI_REGISTRY_IMAGE}/ubuntu/18.04:latest -f Dockerfile_ubuntu_1804 .
    - docker build -t ${CI_REGISTRY_IMAGE}/ubuntu/16.04:latest -f Dockerfile_ubuntu_1604 .
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}/ubuntu:latest
    - docker push ${CI_REGISTRY_IMAGE}/ubuntu/16.04:latest

build:centos:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/centos:latest -f Dockerfile_centos .
    - docker build -t ${CI_REGISTRY_IMAGE}/centos/7:latest -f Dockerfile_centos_7 .
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}/centos:latest
    - docker push ${CI_REGISTRY_IMAGE}/centos/7:latest

external_build:
  image: alpine:latest
  stage: external_build
  only:
    - schedules
  script:
    - apk --no-cache add curl
    - curl -X POST "https://cloud.docker.com/api/build/v1/source/71df786f-d22b-463f-815a-3e861cf2fc33/trigger/cdc498ca-7783-42d0-8685-31d7d6cc555d/call/"
